image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/dev

before_script:
  - cd ${TF_ROOT}

stages:
  - init
  - validate
  - plan
  - deploy

install-terraform:
  stage: init
  script:
    - ls -al
    - terraform init