image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/dev
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/default.tfstate
  GIT_DEPTH: 10

cache:
  key: dev
  paths:
    - ${TF_ROOT}/.terraform
    
before_script:
  - cd ${TF_ROOT}
  - cp ${GOOGLE_CREDENTIALS} > ${TF_ROOT}/key.json

stages:
  - init
  - validate
  - plan
  - apply
  - destroy

install-terraform:
  stage: init
  script:
    - ls -al
    - gitlab-terraform init

validate:
  stage: validate
  script:
    - echo "Validating terraform config files"
    - gitlab-terraform validate
    # - terraform fmt

build:
  stage: plan
  variables:
    TF_VAR_GOOGLE_CREDENTIALS: ${GOOGLE_CREDENTIALS}
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan -json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json
    untracked: false
    expire_in: 30 days

deploy:
  stage: apply
  variables:
    TF_VAR_GOOGLE_CREDENTIALS: ${GOOGLE_CREDENTIALS}
  script:
    - gitlab-terraform apply -auto-approve
  dependencies:
    - build
    
  when: manual

takedown:
  stage: destroy
  variables:
    TF_VAR_GOOGLE_CREDENTIALS: ${GOOGLE_CREDENTIALS}
  script:
    - gitlab-terraform destroy -auto-approve
  # dependencies:
  #   - build

  when: manual