# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Terraform.gitlab-ci.yml

include:
  - template: Terraform/Base.gitlab-ci.yml  # https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Terraform/Base.latest.gitlab-ci.yml

stages:
  - install
  - init
  - validate
  - deploy

install-terraform:
  stage: install
  script:
    - echo "Installing Terraform"
    - wget -O terraform.zip https://releases.hashicorp.com/terraform/0.15.3/terraform_0.15.3_linux_amd64.zip
    - unzip terraform.zip
    - chmod +x terraform
    - sudo mv terraform /usr/local/bin

init:
  extends: .init
  script:
    - echo "Initializing Terraform"

validate:
  extends: .validate
  script:
    - echo "Validating Terraform"

# deploy:
#   extends: .deploy
#   dependencies:
#     - validate
#   script:
#     - echo "Deploying Terraform"